packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - msw
  - prisma
  - sharp
  - unrs-resolver
