"""
Generate the self-contained embedded-font module for the forms renderer.

Fetches the *latin-subset, variable* woff2 for each curated type pairing from
Google Fonts, base64-embeds it as an `@font-face` data-URI, and writes a TS
module. The rendered form HTML then carries its own brand font — works
identically in the file:// preview, the studio iframe (srcDoc), and the Lambda,
with no external requests (CSP: style-src 'unsafe-inline' + font-src data:).

Run from packages/forms-core:  python scripts/gen-fonts.py
"""
import base64
import re
import sys
import urllib.request
from pathlib import Path

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# pairing id -> (css family name used in --tf-font, google css2 query)
FAMILIES = {
    "geist": ("Geist", "family=Geist:wght@100..900"),
    "inter": ("Inter", "family=Inter:wght@100..900"),
    "serif-editorial": ("Fraunces", "family=Fraunces:opsz,wght@9..144,100..900"),
}

FONT_FACE_RE = re.compile(r"@font-face\s*\{(.*?)\}", re.S)


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def latin_woff2_url(css: str) -> str:
    """Return the woff2 src of the basic-latin @font-face block."""
    for block in FONT_FACE_RE.findall(css):
        ur = re.search(r"unicode-range:\s*([^;]+);", block)
        src = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not src:
            continue
        # The basic-latin subset always covers U+0000-00FF.
        if ur and "U+0000-00FF" in ur.group(1):
            return src.group(1)
    # Fallback: last woff2 in the file (Google orders latin last).
    urls = re.findall(r"url\((https://[^)]+\.woff2)\)", css)
    if not urls:
        raise RuntimeError("no woff2 url found")
    return urls[-1]


def main() -> None:
    out_lines = [
        "/**",
        " * GENERATED by scripts/gen-fonts.py — do not edit by hand.",
        " *",
        " * Self-contained `@font-face` declarations (latin-subset variable woff2,",
        " * base64 data-URI) for each curated type pairing. The page renderer inlines",
        " * exactly one of these so a hosted form carries its own brand typography with",
        " * no external request — identical in preview, studio iframe, and production.",
        " */",
        "",
        'import type { TypePairingId } from "../theme.js";',
        "",
        "export const EMBEDDED_FONT_CSS: Partial<Record<TypePairingId, string>> = {",
    ]
    for pairing, (family, query) in FAMILIES.items():
        url = f"https://fonts.googleapis.com/css2?{query}&display=swap"
        css = fetch(url).decode("utf-8")
        woff2_url = latin_woff2_url(css)
        data = fetch(woff2_url)
        b64 = base64.b64encode(data).decode("ascii")
        face = (
            f'@font-face{{font-family:"{family}";font-style:normal;'
            f"font-weight:100 900;font-display:swap;"
            f"src:url(data:font/woff2;base64,{b64}) format(\"woff2\")}}"
        )
        out_lines.append(f'  "{pairing}":')
        out_lines.append(f"    '{face}',")
        print(f"{pairing}: {family} {len(data)//1024}KB woff2 -> {len(b64)//1024}KB base64",
              file=sys.stderr)
    out_lines.append("};")
    out_lines.append("")

    dest = Path(__file__).resolve().parent.parent / "src" / "render" / "fonts.generated.ts"
    dest.write_text("\n".join(out_lines), encoding="utf-8")
    print("wrote", dest, file=sys.stderr)


if __name__ == "__main__":
    main()
