ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SUBMISSION_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SUBMISSION_MODERATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EXPORT_DELIVERY_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'AGENT_ACTION_CREATED';
