ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EXPORT_DELIVERY_READY';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PROJECT_INVITE_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'OUTBOUND_WEBHOOK_DELIVERY_FAILED';
